title: Shashi Kant Gupta
description: "My Homepage"
url: "https://shashikg.github.io"

# paginate: 5
# paginate_path: "/page:num/"
# plugins: [jekyll-paginate]

markdown: kramdown
highlighter: rouge

social-accounts:
  facebook: "shashikg.iitk"
  twitter: "shashikg_iitk"
  youtube: "UCD1ELtVIfZnmIGbfVT9bHXQ"
  github: "shashikg"
  email: "shashikg.iitk@gmail.com"
  linkedin: "in/shashikg"
  google_scholar: "0I5BPCwAAAAJ"

author:
  name: "Shashi Kant Gupta"
  jobTitle: "Data Scientist (Conversational AI)"
  orgName: "RingCentral Innovation (India) Pvt Ltd"
  orgURL: "https://www.ringcentral.com/"

sass:
  sass_dir: _sass
  style: :compressed

# google_analytics:
# disqus_shortname:
